version: '3.8'

services:
  php:
    build: .
    container_name: php-container
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www
  web_server:
    container_name: server_nginx
    image: nginx:alpine
    ports:
      - "8080:80"
  database:
    container_name: mysql_db
    image: mysql:5.7.22
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
