version: '3.8'

services:
  php:
    build: .
    container_name: php-container
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www
  web_server:
    container_name: server_nginx
    image: nginx:alpine
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  database:
    container_name: mysql_db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'toxindzners'
      MYSQL_DATABASE: 'auth_symf'
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
  swagger:
    container_name: swagger_ui
    image: swaggerapi/swagger-ui
    ports:
      - "90:8080"